### PR TITLE
GCW-2387 Don't show order notification to Donor and Admin app

### PR DESCRIPTION
**Pull request by Darshan-Chauhan**
Hi Team,

This PR fixes Admin: something went wrong after submitting an appointment on Browse
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2387

Please review

### CODE REVIEW

**Comment by steveyken** [comment]
Why is the new order notification being sent to the donor and admin apps? We shouldn't need to be fixing the problem here. We should fix the API instead. Am I missing anything?

**Comment by Darshan-Chauhan** [comment]
@steveyken , the notification is sent based on user role. So if user with role order fulfillment is logged in to any app, he or she will get notification.
I just fixed the problem on front end side for time being as back end notification implementation needs to restructure and that may take some time so

**Comment by steveyken** [comment]
I see. I think we had the notion of user channels that were specific to apps. so for example when User 1 logs in to the admin app, they subscribe to the channel `user_1_admin`. We should be doing same for stock and browse. cc @namrataukirde @abhinav098

**Comment by abhinav098** [comment]
> We should be doing same for stock and browse

We have done it the same way @steveyken , for browse app, we suffix the `browse` string with `user_#{id}_`, and similarly for stock.

**Comment by steveyken** [comment]
Great, then I'd advocate rolling back this change here as we shouldn't need it. Thanks for having it in the interim.

**Comment by Darshan-Chauhan** [comment]
@steveyken , we still need this as @abhinav098 's feature only handles messages and not notification for new order

**Pull request merged**
